server:
  ip: localhost
  port: 9090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #?Spring Boot 2.6.x ?Swagger 3.0.0 ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?serverTimezone=GMT%2b8
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????????????????????????????????????? address_book ---> addressBook
    map-underscore-to-camel-case: true